CREATE TABLE ai_providers
(
    id                 VARCHAR(255) NOT NULL,
    name               VARCHAR(255),
    provider           SMALLINT,
    base_url           VARCHAR(255),
    api_key            VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_providers PRIMARY KEY (id)
);

CREATE TABLE chat_attatchments
(
    id                 VARCHAR(255) NOT NULL,
    file_id            VARCHAR(255),
    file_name          VARCHAR(255),
    content_type       SMALLINT,
    mime_type          VARCHAR(255),
    chat_session_id    VARCHAR(255),
    chat_message_id    VARCHAR(255),
    extracted_text     TEXT,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    is_used            BOOLEAN      NOT NULL,
    CONSTRAINT pk_chat_attatchments PRIMARY KEY (id)
);

CREATE TABLE chat_memory
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_session_id VARCHAR(255),
    messages        TEXT,
    CONSTRAINT pk_chat_memory PRIMARY KEY (id)
);

CREATE TABLE chat_messages
(
    id                 VARCHAR(255) NOT NULL,
    chat_session_id    VARCHAR(255),
    message            TEXT,
    message_type       SMALLINT,
    attachments        TEXT[],
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id)
);

CREATE TABLE chat_sessions
(
    id                 VARCHAR(255) NOT NULL,
    user_id            VARCHAR(255),
    title              VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_chat_sessions PRIMARY KEY (id)
);

CREATE TABLE files
(
    id                 VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    storage_path       VARCHAR(255) NOT NULL,
    stored_name        VARCHAR(255) NOT NULL,
    size               BIGINT       NOT NULL,
    user_id            VARCHAR(255) NOT NULL,
    is_used            BOOLEAN      NOT NULL,
    mime_type          VARCHAR(255) NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_files PRIMARY KEY (id)
);

CREATE TABLE ll_models
(
    id                      VARCHAR(255) NOT NULL,
    public_name             VARCHAR(255),
    origin_name             VARCHAR(255),
    provider_id             VARCHAR(255),
    completion_url          VARCHAR(255),
    is_custom_system_prompt BOOLEAN      NOT NULL,
    system_prompt_id        BIGINT,
    created_date            TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ll_models PRIMARY KEY (id)
);

CREATE TABLE prompts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    purpose     SMALLINT,
    prompt      TEXT,
    CONSTRAINT pk_prompts PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 VARCHAR(255) NOT NULL,
    username           VARCHAR(255) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    roles              VARCHAR(255) NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);